### ISSUE TITLE
To suggest design history of the games page

### ISSUE THREAD

**Issue by VadymSula** [VadymSula/mafia-helper#54]
1. Create request for connecting to [Whimsical](https://whimsical.com/JiyM8i23h2Uh8K8ekEpQTs) in [my telegram](https://t.me/VadymSula) about your reading. (Checking your activity)
2. To suggest an design-idea history of the games (in whimsical.com)
![изображение.png](https://images.zenhubusercontent.com/5defe4c5ae8d3341bb8aecb8/f9107304-2e61-448d-9f22-21a0ee94d25c)
3. Info in page:
- List of the games (Info: start-time, game duration, winner(mafia or city))   *Create only 1 game-example
- Create unfolding list this game(Info: Lead-nickname, game-features)

- [x] Danila
- [ ] Nastia
- [ ] Misha

**Comment by dokspy** [comment]
I done design history of the games page!
